NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.cluster2.authdee.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.cluster2.authdee.com-cert.pem
    OrganizationalUnitIdentifier: peer
