OrdererOrgs:
  - Name: Orderer
    Domain: authdee.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Cluster1
    Domain: cluster1.authdee.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Cluster2
    Domain: cluster2.authdee.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
